version: "3.5"
services:
  keyrock:
    image: fiware/idm:7.9.0
    container_name: fiware-keyrock
    hostname: keyrock
    networks:
      default:
        ipv4_address: 172.18.1.5
    depends_on:
      - mysql-db
    ports:
      - "3000:3000"
      - "443:443"
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=mysql-db
      - IDM_HOST=http://localhost:3000
      - IDM_PORT=3000
      # Development use only 
      # Use Docker Secrets for Sensitive Data
      - IDM_DB_PASS=secret 
      - IDM_DB_USER=root
      - IDM_ADMIN_USER=admin
      - IDM_ADMIN_EMAIL=admin@test.com
      - IDM_ADMIN_PASS=1234
      # If sending eMails point to any STMP server
      - IDM_EMAIL_HOST=mailer
      - IDM_EMAIL_PORT=25

  mysql-db:
    restart: always
    image: mysql:5.7
    hostname: mysql-db
    container_name: db-mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: 172.18.1.6
    environment:
      # Development use only 
      # Use Docker Secrets for Sensitive Data
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_ROOT_HOST=172.18.1.5"
    volumes:
      - mysql-db:/var/lib/mysql

  # Configure the SMTP settings below as necessary,
  # For example to use Gmail SMTP
  #
  # server address: smtp.gmail.com
  # username: Your Gmail address (for example, example@gmail.com)
  # password: Your Gmail password
  # port (TLS): 587
  # port (SSL): 465
  # TLS/SSL required: Yes

  mailer:
    restart: always
    image: mazdermind/docker-mail-relay
    hostname: mailer
    container_name: mailer
    ports:
      - "25:25"
    environment:
      - SMTP_LOGIN=<login> # Login to connect to the external relay
      - SMTP_PASSWORD=<password> # Password to connect to the external relay
      - EXT_RELAY_HOST=<hostname> # External relay DNS name
      - EXT_RELAY_PORT=25
      - ACCEPTED_NETWORKS=172.18.1.0/24
      - USE_TLS=no


networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
volumes:
  mysql-db: ~
